# This is a basic workflow to help you get started with Actions

name: mvn-test

on: [push]

#env:
 # chrome-version: "119.0.6029.0"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Chrome Driver  
        run: python .github/bin/chromeDriver.py 

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Setup path
        run: echo "${{ github.workspace }}/chrome/chromedriver-linux64:${{ github.workspace }}/chrome/chrome-linux64" >> $GITHUB_PATH

      - name: Start chrome
        run: chrome --headless --disable-gpu    

      - name: Print path
        run: echo "$PATH"

      - name: Check driver version
        run: chromedriver --version  

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
        env:
            SE_BROWSER_PATH: "${{ github.workspace }}/chrome/chrome-linux64"

